a1 = float(input("Enter value of a1: "))
a2 = float(input("Enter value of a2: "))
a3 = float(input("Enter value of a3: "))
b1 = float(input("Enter value of b1: "))
b2 = float(input("Enter value of b2: "))
b3 = float(input("Enter value of b3: "))
dp = (a1 * b1) + (a2 * b2) + (a3 * b3)
print("Dot product of both vector is: ", dp)
print("Scalar product")
